services:
  library_app:
    container_name: library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/asap_demo_library
    env_file:
      - .env
    command: > 
      sh -c "python manage.py wait_for_db_script && 
      python manage.py migrate && 
      python manage.py loaddata sample_data.json &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - my_network

  tests:
    container_name: tests-books
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my_network
    command: >
      sh -c "python manage.py wait_for_db_script && 
      python manage.py test books_app"

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:$PGDATA
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge
